ProyectoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


# from mainapp import views
# from pages import views as page_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('', include('pages.urls')),
    path('', include('blog.urls')),
    

    
    # path('', views.index, name="index"),
    # path('inicio/', views.index, name="index"),
    # path('pagina/<str:slug>', page_views.page, name="page"),
]

#Ruta imagenes
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('articulos', views.list, name="list_articles"),
    path('categoria/<int:category_id>', views.category, name="category"),
    path('articulo/<int:article_id>', views.article, name="article")
]

mainapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('inicio/', views.index, name="inicio"),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pagina/<str:slug>', views.page, name="page")
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField( max_length=100, verbose_name="Nombre" )
    description = models.CharField( max_length=255, verbose_name="Descripción" )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ['created_at']

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField( max_length=150, verbose_name="Titulo" )
    content = RichTextField( verbose_name="Contenido" )
    image = models.ImageField( default='null', verbose_name="Imagen", upload_to="articles" )
    public = models.BooleanField( verbose_name="Publicado?")
    user = models.ForeignKey(User, editable=False, verbose_name="Usuario", on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, blank=True, verbose_name="Categorias")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Editado el")

    class Meta:
        verbose_name = "Articulo"
        verbose_name_plural = "Articulos"

    def __str__(self):
        return self.title

mainapp/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Page(models.Model):
    title = models.CharField( max_length=100, verbose_name="Titulo" )
    content = RichTextField( verbose_name="Contenido" )
    # TODO: aca es slug 
    public = models.CharField( unique=True, max_length=150, verbose_name="URL amigable" )
    order = models.IntegerField(default=0, verbose_name="Order")
    visible = models.BooleanField( verbose_name="Visible?")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    class Meta:
        verbose_name = "Pagina"
        verbose_name_plural = "Paginas"

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Category, Article

# Create your views here.
def list(request):

    articles = Article.objects.all()

    return render(request, 'articles/list.html', {
        'title': 'Articulos',
        'articles': articles
    })


def category(request, category_id):

    # TODO: asi se hace una consulta a la BD
    # category = get_object_or_404(Category, id=category_id)
    category = Category.objects.get(id=category_id)
    # articles = Article.objects.filter(categories=category)

    # TODO: llama al template
    return render(request, 'categories/category.html', {
        'category': category,
        # 'articles':articles
    })

def article(request, article_id):

    # TODO: asi se hace una consulta a la BD
    # category = get_object_or_404(Category, id=category_id)
    article = Article.objects.get(id=article_id)
    # articles = Article.objects.filter(categories=category)

    # TODO: llama al template
    return render(request, 'articles/detail.html', {
        'article': article,
        # 'articles':articles
    })

mainapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'mainapp/index.html', {
        'title': 'Inicio'
    })

# def about(request):
#     return render(request, 'mainapp/about.html', {
#         'title': 'Sobre mi'
#     })

pages/views.py
from django.shortcuts import render
from .models import Page

# Create your views here.
def page(request, slug):

    page = Page.objects.get(public=slug);

    return render(request, "pages/page.html", {
        "page": page
    })

blog/templates/articles/articles.html
{% for a in articles %}
<article class="article-item">
	{% if a.image != 'null' and a.image.url|length >= 1 %}
		<div class="image">
			<img src="{{ a.image.url }}" alt="">
		</div>
	{% endif %}

	<div class="data">
		<a href="{% url  'article' a.id %}"><h2>{{a.title}}</h2></a>
		
		<p>
			{% for c in a.categories.all %}
				<a href="{% url 'category' c.id %}">{{c.name}}</a>

				{% if forloop.counter < a.categories.all|length %}
					{{'-'}}
				{% endif %}
			{% endfor %}
		</p>
		<span class="date">
			{{a.user.first_name}} {{a.user.last_name}}
			|
			{{a.created_at}}
		</span>
		<p>
			{{a.content|safe}}
		</p>
	</div>
</article>

{% endfor %}

blog/templates/articles/detail.html
{% extends 'layouts/layout.html' %}


{% block title %}
	{{article.title}}
{% endblock %}

{% block content %}
	{% if article.image != 'null' and article.image.url|length >= 1 %}
	<div class="image">
		<img src="{{ article.image.url }}" alt="">
	</div>
	{% endif %}
	<h1> {{article.title}} </h1>
	<span>{{article.created_at}}</span>
	<p>
		{{article.content|safe}}
	</p>
{% endblock %}

blog/templates/articles/list.html
{% extends 'layouts/layout.html' %}


{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	<h1> {{title}} </h1>

	{% include 'articles/articles.html' %}
{% endblock %}

blog/templates/categories/category.html
{% extends 'layouts/layout.html' %}


{% block title %}
	{{category.name}}
{% endblock %}

{% block content %}
	<h1> {{category.name}} </h1>
	<p>{{ category.description}}</p>

	<!-- TODO: llama a los articulos dentro de una categoria -->
	{% include 'articles/articles.html' with articles=category.article_set.all %}
{% endblock %}

mainapp/templates/layouts/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>
		{% block title %}
		{% endblock %}
		| Echeverria Juan
	</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
	{% load static %}

	<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
	<script src="{% static 'js/jquery.waypoints.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script src="{% static 'js/scripts.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
	<script type="text/javascript">
		var wow = new WOW({
		 boxClass:     'wow',      // animated element css class (default is wow)
		 animateClass: 'animated', // animation css class (default is animated)
		 offset:       0,          // distance to the element when triggering the animation (default is 0)
		 mobile:       true,       // trigger animations on mobile devices (default is true)
		 live:         true,       // act on asynchronously loaded content (default is true)
		 callback:     function(box) {
		   // the callback is fired every time an animation is started
		   // the argument that is passed in is the DOM node being animated
		 },
		 scrollContainer: null,    // optional scroll container selector, otherwise use window,
		 resetAnimation: true,     // reset animation on end (default is true)
		  });
		wow.init();
		</script>
</head>
<body>
	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col-6">
					<div class="logo">
						<img src="{% static 'images/logo.png' %}">
					</div>
				</div>
				<div class="col-6 d-flex justify-content-end align-items-center">
					<div class="contenedor_menu">
						<nav class="top">
							<!-- <a href="https://www.facebook.com/Noreste-Fabricando-Ideas-2205327093130282/"><i class="fab fa-facebook"></i></a> -->
							<p class="lang" key="slogan">Diseño y Desarrollo Web ^^</p>
							<!-- <a href="https://www.instagram.com/noresteideas/?hl=es-la"><i class="fab fa-instagram"></i></a> -->
						  </nav>
						<nav class="navegacion-principal">
							<ul class="menu-list list-inline">
								<li class="list-inline-item">
									<a href="/inicio">Inicio</a>
								</li>
								{% for page in pages %}
									<li class="list-inline-item">
										<a href="{% url 'page' page.2 %}">{{page.1}}</a>
									</li>
								{% endfor %}
								<li class="list-inline-item category">
									<a href={% url 'list_articles' %}>Categorias</a>
									<ul class="submenu">
										{% for c in categories%}
										<li><a href="{% url 'category' c.0 %}">{{c.1}}</a></li>
										{% endfor %}
									</ul>
								</li>
							</ul>
						</nav>
					</div>
					<div class="hamburger">
						<div class="hamburger-inner"></div>
					  </div>
				</div>
			</div>
		</div>

	</header>



	<div class="content">
		<div class="box">
			{% block content %}
			<!-- codigo de los templates -->
			{% endblock %}
		</div>
	</div>

	<footer class="footer py-2 text-center">
		<div class="container">
		  <p>2021 JME Development</p>
		</div>
	  </footer>

</body>
</html>

mainapp/templates/mainapp/about.html
{% extends 'layouts/layout.html' %}


{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	<h1> {{title}} </h1>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'layouts/layout.html' %}

{% block title %}
	{{title}}
{% endblock %}

{% block content %}




	<section class="servicios">
		<div class="contenedor-video">
		  <video autoplay loop muted poster="">
			<source src="../../static/images/video.mp4" type="video/mp4">
		  </video>
		  <div class="data container">
			<div class="row">
			  <div class="col-12 col-lg-5 pb-lg-0 pb-5">
				<div class="logo wow zoomIn">
				  <img src="../../static/images/logo.png" alt="logo" class="img-fluid glow"> 
				</div>
			 
				<div class="title wow fadeIn" data-wow-delay="0.1s">
					<h1> {{title}} </h1>
				</div>
	
				</h2>
			  </div>
			  <div class="items col-12 col-lg-7 d-flex align-items-center">
				<div class="row">
				
				  <div class="item col-12 col-md-6 pb-3 pb-md-0 wow fadeIn" data-wow-delay="0.3s">
					<div class="row">
					  <div class="col-3 mt-1">
						<i class="fas fa-desktop pr-3"></i>
					  </div>
					  <div class="col-9">
						<h3 class="text-left">Diseño Web</h3>
						<p class="text-left">Diseño y programación de sitios Web, paginas informativas, landing-pages, diseños exclusivos y a medida según tu necesidad. </p>
					  </div>
					</div>
				  </div>
	
	
				  <div class="item col-12 col-md-6 pb-3 pb-md-0 wow fadeIn" data-wow-delay="0.5s">
					<div class="row">
					  <div class="col-3 mt-1">
						<i class="fas fa-shopping-bag"></i>
					  </div>
					  <div class="col-9">
						<h3 class="text-left">E-commerce</h3>
						<p class="text-left">Tu tienda online autoadmisitrable. Soluciones personalizadas de Ecommerce y Venta Directa.</p>
					  </div>
					</div>
				  </div>
	
				  <div class="item col-12 col-md-6 pb-3 pb-md-0 wow fadeIn" data-wow-delay="0.7s">
					<div class="row">
					  <div class="col-3 mt-1">
						<i class="fas fa-mobile-alt"></i>
					  </div>
					  <div class="col-9">
						<h3 class="text-left">Mobile App</h3>
						<p class="text-left">Desarrollo y subo tu App a la Play Store de Android. Tu App vinculada a tu sitio personal o E-commerce siempre actualizada</p>
					  </div>
					</div>
				  </div>
	
			  </div>
	  
			</div>
		  </div>
		</div><!-- contenedor video -->
	
	  </section>
	
	  <section id="portfolio" class="portfolio">
	
		<div class="contador parallax">
			<div class="contenedor">
			  <ul class="resumen-evento clearfix">
				<li><p class="numero">0</p>Invitados</li>
				<li><p class="numero">0</p>Talleres</li>
				<li><p class="numero">0</p>Dias</li>
				<li><p class="numero">0</p>Conferencias</li>
			  </ul>
			</div>
		  </div> <!--parallax-->
	  </section>
	
	
	
	  <section id="contacto" class="contacto text-center">
		<div class="container">
		  <h2>Información de contacto</h2>
		  <div class="row">
			<div class="col-xl-12">
			  <ul>
				<li><i class="fas fa-envelope"></i>&nbsp;MAIL: <a
					href="mailto:echeverriajm@yahoo.com.ar">echeverriajm@yahoo.com.ar</a></li>
				<!-- <li><i class="fas fa-phone"></i>&nbsp;TÉLEFONO: <a href="tel:3434729353">343-4729353</a></li> -->
				<li><i class="fab fa-whatsapp"></i>&nbsp;WHATSAPP: <a href="https://wa.me/5493434729353">+5493434729353</a>
				</li>
				<!-- <li><i class="fab fa-facebook"></i>&nbsp;FACEBOOK: <a
					href="https://www.facebook.com/takelo">facebook/echeverriajm</a></li> -->
				<!-- <li><i class="fas fa-map-marker-alt"></i>&nbsp;DIRECCIÓN: Ricardo Balbin y Gobernador Enrique Mihura</li> -->
				<!-- <li><i class="fas fa-clock"></i>&nbsp;HORARIOS: Lunes a Viernes – 8:00hs a 17:00hs</li> -->
			  </ul>
			</div>
		  </div>
		  <div class="row">
			<div class="col-xl-12">
			  <div id="contacto" class="contacto">
				<h3>O completa el formulario</h3>
				<form method="post" action="https://formspree.io/factorzero@gmail.com">
				  <div class="field half first">
					<input type="text" name="name" id="name" placeholder="Nombre" />
				  </div>
				  <div class="field half">
					<input type="email" name="email" id="email" placeholder="Mail" />
				  </div>
				  <div class="field">
					<textarea name="message" id="message" placeholder="Mensaje"></textarea>
				  </div>
				  <input class="btn btn-secondary btn-lg" type="submit" value="Enviar" class="special" />
	
				</form>
				</form>
			  </div>
			</div>
		  </div>
		</div>
	  </section> 
{% endblock %}

pages/templates/pages/page.html
{% extends 'layouts/layout.html' %}


{% block title %}
	{{page.title}}
{% endblock %}

{% block content %}
	<h1> {{page.title}} </h1>
	<span>{{page.created_at}}</span>
	<p>
		{{page.content|safe}}
	</p>
{% endblock %}